# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cos/CLionProjects/bastet-remotable

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cos/CLionProjects/bastet-remotable

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cos/CLionProjects/bastet-remotable/CMakeFiles /home/cos/CLionProjects/bastet-remotable/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cos/CLionProjects/bastet-remotable/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bastet

# Build rule for target.
bastet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bastet
.PHONY : bastet

# fast build rule for target.
bastet/fast:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/build
.PHONY : bastet/fast

BastetBlockChooser.o: BastetBlockChooser.cpp.o

.PHONY : BastetBlockChooser.o

# target to build an object file
BastetBlockChooser.cpp.o:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/BastetBlockChooser.cpp.o
.PHONY : BastetBlockChooser.cpp.o

BastetBlockChooser.i: BastetBlockChooser.cpp.i

.PHONY : BastetBlockChooser.i

# target to preprocess a source file
BastetBlockChooser.cpp.i:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/BastetBlockChooser.cpp.i
.PHONY : BastetBlockChooser.cpp.i

BastetBlockChooser.s: BastetBlockChooser.cpp.s

.PHONY : BastetBlockChooser.s

# target to generate assembly for a file
BastetBlockChooser.cpp.s:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/BastetBlockChooser.cpp.s
.PHONY : BastetBlockChooser.cpp.s

Block.o: Block.cpp.o

.PHONY : Block.o

# target to build an object file
Block.cpp.o:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/Block.cpp.o
.PHONY : Block.cpp.o

Block.i: Block.cpp.i

.PHONY : Block.i

# target to preprocess a source file
Block.cpp.i:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/Block.cpp.i
.PHONY : Block.cpp.i

Block.s: Block.cpp.s

.PHONY : Block.s

# target to generate assembly for a file
Block.cpp.s:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/Block.cpp.s
.PHONY : Block.cpp.s

BlockChooser.o: BlockChooser.cpp.o

.PHONY : BlockChooser.o

# target to build an object file
BlockChooser.cpp.o:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/BlockChooser.cpp.o
.PHONY : BlockChooser.cpp.o

BlockChooser.i: BlockChooser.cpp.i

.PHONY : BlockChooser.i

# target to preprocess a source file
BlockChooser.cpp.i:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/BlockChooser.cpp.i
.PHONY : BlockChooser.cpp.i

BlockChooser.s: BlockChooser.cpp.s

.PHONY : BlockChooser.s

# target to generate assembly for a file
BlockChooser.cpp.s:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/BlockChooser.cpp.s
.PHONY : BlockChooser.cpp.s

BlockPosition.o: BlockPosition.cpp.o

.PHONY : BlockPosition.o

# target to build an object file
BlockPosition.cpp.o:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/BlockPosition.cpp.o
.PHONY : BlockPosition.cpp.o

BlockPosition.i: BlockPosition.cpp.i

.PHONY : BlockPosition.i

# target to preprocess a source file
BlockPosition.cpp.i:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/BlockPosition.cpp.i
.PHONY : BlockPosition.cpp.i

BlockPosition.s: BlockPosition.cpp.s

.PHONY : BlockPosition.s

# target to generate assembly for a file
BlockPosition.cpp.s:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/BlockPosition.cpp.s
.PHONY : BlockPosition.cpp.s

Config.o: Config.cpp.o

.PHONY : Config.o

# target to build an object file
Config.cpp.o:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/Config.cpp.o
.PHONY : Config.cpp.o

Config.i: Config.cpp.i

.PHONY : Config.i

# target to preprocess a source file
Config.cpp.i:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/Config.cpp.i
.PHONY : Config.cpp.i

Config.s: Config.cpp.s

.PHONY : Config.s

# target to generate assembly for a file
Config.cpp.s:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/Config.cpp.s
.PHONY : Config.cpp.s

JsonSocket.o: JsonSocket.cpp.o

.PHONY : JsonSocket.o

# target to build an object file
JsonSocket.cpp.o:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/JsonSocket.cpp.o
.PHONY : JsonSocket.cpp.o

JsonSocket.i: JsonSocket.cpp.i

.PHONY : JsonSocket.i

# target to preprocess a source file
JsonSocket.cpp.i:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/JsonSocket.cpp.i
.PHONY : JsonSocket.cpp.i

JsonSocket.s: JsonSocket.cpp.s

.PHONY : JsonSocket.s

# target to generate assembly for a file
JsonSocket.cpp.s:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/JsonSocket.cpp.s
.PHONY : JsonSocket.cpp.s

Ui.o: Ui.cpp.o

.PHONY : Ui.o

# target to build an object file
Ui.cpp.o:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/Ui.cpp.o
.PHONY : Ui.cpp.o

Ui.i: Ui.cpp.i

.PHONY : Ui.i

# target to preprocess a source file
Ui.cpp.i:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/Ui.cpp.i
.PHONY : Ui.cpp.i

Ui.s: Ui.cpp.s

.PHONY : Ui.s

# target to generate assembly for a file
Ui.cpp.s:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/Ui.cpp.s
.PHONY : Ui.cpp.s

Well.o: Well.cpp.o

.PHONY : Well.o

# target to build an object file
Well.cpp.o:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/Well.cpp.o
.PHONY : Well.cpp.o

Well.i: Well.cpp.i

.PHONY : Well.i

# target to preprocess a source file
Well.cpp.i:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/Well.cpp.i
.PHONY : Well.cpp.i

Well.s: Well.cpp.s

.PHONY : Well.s

# target to generate assembly for a file
Well.cpp.s:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/Well.cpp.s
.PHONY : Well.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/bastet.dir/build.make CMakeFiles/bastet.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... bastet"
	@echo "... BastetBlockChooser.o"
	@echo "... BastetBlockChooser.i"
	@echo "... BastetBlockChooser.s"
	@echo "... Block.o"
	@echo "... Block.i"
	@echo "... Block.s"
	@echo "... BlockChooser.o"
	@echo "... BlockChooser.i"
	@echo "... BlockChooser.s"
	@echo "... BlockPosition.o"
	@echo "... BlockPosition.i"
	@echo "... BlockPosition.s"
	@echo "... Config.o"
	@echo "... Config.i"
	@echo "... Config.s"
	@echo "... JsonSocket.o"
	@echo "... JsonSocket.i"
	@echo "... JsonSocket.s"
	@echo "... Ui.o"
	@echo "... Ui.i"
	@echo "... Ui.s"
	@echo "... Well.o"
	@echo "... Well.i"
	@echo "... Well.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

